// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eachi_cpp
extern "C" double eachi_cpp(SEXP jS, SEXP sS, SEXP tS, SEXP mS, SEXP xoyS, SEXP uS);
RcppExport SEXP _scale_eachi_cpp(SEXP jSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP mSSEXP, SEXP xoySSEXP, SEXP uSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type jS(jSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xoyS(xoySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uS(uSSEXP);
    rcpp_result_gen = Rcpp::wrap(eachi_cpp(jS, sS, tS, mS, xoyS, uS));
    return rcpp_result_gen;
END_RCPP
}
// eadel_cpp
extern "C" double eadel_cpp(SEXP nS, SEXP sS, SEXP tS, SEXP xS, SEXP yS, SEXP mS, SEXP uS);
RcppExport SEXP _scale_eadel_cpp(SEXP nSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP xSSEXP, SEXP ySSEXP, SEXP mSSEXP, SEXP uSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xS(xSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uS(uSSEXP);
    rcpp_result_gen = Rcpp::wrap(eadel_cpp(nS, sS, tS, xS, yS, mS, uS));
    return rcpp_result_gen;
END_RCPP
}
// eadel_pair_cpp
extern "C" Rcpp::NumericVector eadel_pair_cpp(SEXP nS, SEXP sS, SEXP tS, SEXP xS, SEXP yS, SEXP mS, SEXP uS);
RcppExport SEXP _scale_eadel_pair_cpp(SEXP nSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP xSSEXP, SEXP ySSEXP, SEXP mSSEXP, SEXP uSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xS(xSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uS(uSSEXP);
    rcpp_result_gen = Rcpp::wrap(eadel_pair_cpp(nS, sS, tS, xS, yS, mS, uS));
    return rcpp_result_gen;
END_RCPP
}
// eadel2_cpp
extern "C" double eadel2_cpp(SEXP nS, SEXP sS, SEXP tS, SEXP mS, SEXP xoyS, SEXP uS);
RcppExport SEXP _scale_eadel2_cpp(SEXP nSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP mSSEXP, SEXP xoySSEXP, SEXP uSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xoyS(xoySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uS(uSSEXP);
    rcpp_result_gen = Rcpp::wrap(eadel2_cpp(nS, sS, tS, mS, xoyS, uS));
    return rcpp_result_gen;
END_RCPP
}
// eagamma_cpp
extern "C" double eagamma_cpp(SEXP nS, SEXP sS, SEXP tS, SEXP xS, SEXP yS, SEXP LS, SEXP US);
RcppExport SEXP _scale_eagamma_cpp(SEXP nSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP xSSEXP, SEXP ySSEXP, SEXP LSSEXP, SEXP USSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xS(xSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type LS(LSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type US(USSEXP);
    rcpp_result_gen = Rcpp::wrap(eagamma_cpp(nS, sS, tS, xS, yS, LS, US));
    return rcpp_result_gen;
END_RCPP
}
// eapsi_cpp
extern "C" double eapsi_cpp(SEXP jS, SEXP sS, SEXP tS, SEXP mS, SEXP xoyS, SEXP uS);
RcppExport SEXP _scale_eapsi_cpp(SEXP jSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP mSSEXP, SEXP xoySSEXP, SEXP uSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type jS(jSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xoyS(xoySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uS(uSSEXP);
    rcpp_result_gen = Rcpp::wrap(eapsi_cpp(jS, sS, tS, mS, xoyS, uS));
    return rcpp_result_gen;
END_RCPP
}
// eazeta_cpp
extern "C" double eazeta_cpp(SEXP nS, SEXP sS, SEXP tS, SEXP xS, SEXP yS, SEXP LS, SEXP US);
RcppExport SEXP _scale_eazeta_cpp(SEXP nSSEXP, SEXP sSSEXP, SEXP tSSEXP, SEXP xSSEXP, SEXP ySSEXP, SEXP LSSEXP, SEXP USSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nS(nSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sS(sSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tS(tSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xS(xSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yS(ySSEXP);
    Rcpp::traits::input_parameter< SEXP >::type LS(LSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type US(USSEXP);
    rcpp_result_gen = Rcpp::wrap(eazeta_cpp(nS, sS, tS, xS, yS, LS, US));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scale_eachi_cpp", (DL_FUNC) &_scale_eachi_cpp, 6},
    {"_scale_eadel_cpp", (DL_FUNC) &_scale_eadel_cpp, 7},
    {"_scale_eadel_pair_cpp", (DL_FUNC) &_scale_eadel_pair_cpp, 7},
    {"_scale_eadel2_cpp", (DL_FUNC) &_scale_eadel2_cpp, 6},
    {"_scale_eagamma_cpp", (DL_FUNC) &_scale_eagamma_cpp, 7},
    {"_scale_eapsi_cpp", (DL_FUNC) &_scale_eapsi_cpp, 6},
    {"_scale_eazeta_cpp", (DL_FUNC) &_scale_eazeta_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_scale(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
