# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eachi_cpp <- function(jS, sS, tS, mS, xoyS, uS) {
    .Call('_scale_eachi_cpp', PACKAGE = 'scale', jS, sS, tS, mS, xoyS, uS)
}

eadel_cpp <- function(nS, sS, tS, xS, yS, mS, uS) {
    .Call('_scale_eadel_cpp', PACKAGE = 'scale', nS, sS, tS, xS, yS, mS, uS)
}

eadel_pair_cpp <- function(nS, sS, tS, xS, yS, mS, uS) {
    .Call('_scale_eadel_pair_cpp', PACKAGE = 'scale', nS, sS, tS, xS, yS, mS, uS)
}

eadel2_cpp <- function(nS, sS, tS, mS, xoyS, uS) {
    .Call('_scale_eadel2_cpp', PACKAGE = 'scale', nS, sS, tS, mS, xoyS, uS)
}

eagamma_cpp <- function(nS, sS, tS, xS, yS, LS, US) {
    .Call('_scale_eagamma_cpp', PACKAGE = 'scale', nS, sS, tS, xS, yS, LS, US)
}

eapsi_cpp <- function(jS, sS, tS, mS, xoyS, uS) {
    .Call('_scale_eapsi_cpp', PACKAGE = 'scale', jS, sS, tS, mS, xoyS, uS)
}

eazeta_cpp <- function(nS, sS, tS, xS, yS, LS, US) {
    .Call('_scale_eazeta_cpp', PACKAGE = 'scale', nS, sS, tS, xS, yS, LS, US)
}

